sudo: required
services:
  - docker

before_install:
  - docker build -t dariuszdyrda/react-test -f ./todo-client/Dockerfile.dev ./todo-client

script:
  - docker run dariuszdyrda/react-test npm test -- --coverage

after_success:
  - docker build -t dariuszdyrda/multi-client ./todo-client
  - docker build -t dariuszdyrda/multi-nginx ./nginx
  - docker build -t dariuszdyrda/multi-api ./TodoAPI
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dariuszdyrda/multi-client
  - docker push dariuszdyrda/multi-nginx
  - docker push dariuszdyrda/multi-api

  deploy:
    provider: gae
    keyfile: ./computeEngineServiceKey.json
    on:
      branch: master
    project: todo-microservices
