version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
  app:
    container_name: todoapi
    restart: always
    build: ./TodoAPI
    image: debian/latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  client:
    container_name: todo-client
    restart: always
    build: ./todo-client
    ports:
      - "80:3000"

volumes:
  data-volume: