version: "3"
services:
  mongo:
    image: mongo:latest
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./TodoAPI
    environment:
      - mongoURL=mongodb://mongo:27017/todos
    volumes:
      - /app/node_modules
      - ./TodoAPI:/usr/src/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./todo-client
    volumes:
      - /app/node_modules
      - ./todo-client:/usr/src/app