version: "2"
services:
  app:
    container_name: todoapi
    restart: always
    build: ./TodoAPI
    image: debian/latest
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  client:
    container_name: todo-client
    restart: always
    build: ./todo-client
    ports:
      - "80:3000"
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"

volumes:
  data-volume: