version: "2"
volumes:
  mongodata:
services:
  app:
    container_name: todoapi
    restart: always
    build: ./TodoAPI
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"