version: "3"
services:
  mongo:
    image: mongo:latest
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./TodoAPI
    environment:
      #- mongoURL=mongodb://mongo:27017/todos
      #ONLY FOR DEVELOPMENT
      - mongoURL=mongodb://admin:admin123@ds135726.mlab.com:35726/todos-test
    volumes:
      - /app/node_modules
      - ./TodoAPI:/usr/src/app
    command: npm run dev
  client:
    volumes:
      - /todo-client/node_modules
      - ./todo-client/:/usr/src/app
    build:
      dockerfile: Dockerfile.dev
      context: ./todo-client
    command: npm start